import os
# from dotenv import load_dotenv
# from utils.keyvault import get_secret

# load_dotenv()

##### FILL IN MANUALLY ######
KEY_VAULT_URL = os.environ.get("KEY_VAULT_URL") #  os.environ.get("KEY_VAULT_URL")

DEVELOPMENT = True

if DEVELOPMENT:
    # OPENAI_AZURE_ENDPOINT = os.environ.get("OPENAI_AZURE_ENDPOINT")
    # OPENAI_API_VERSION = os.environ.get("OPENAI_API_VERSION")
    # OPENAI_DEPLOYMENT_NAME = os.environ.get("OPENAI_DEPLOYMENT_NAME")
    # OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
    # OPENAI_API_TYPE = os.environ.get("OPENAI_API_TYPE")
    # OPENAI_MODEL_NAME = os.environ.get("OPENAI_MODEL_NAME")

    # STORAGE_ACCOUNT_NAME = os.environ.get("STORAGE_ACCOUNT_NAME") 
    # STORAGE_ACCOUNT_KEY = os.environ.get("STORAGE_ACCOUNT_KEY") 

    # COSMOS_DB_ACCOUNT_URI = os.environ.get("COSMOS_DB_ACCOUNT_URI")
    # COSMOS_DB_ACCOUNT_KEY = os.environ.get("COSMOS_DB_ACCOUNT_KEY")
    # COSMOS_DB_DATABASE_NAME = os.environ.get("COSMOS_DB_DATABASE_NAME")
    # COSMOS_DB_CONTAINER_NAME = os.environ.get("COSMOS_DB_CONTAINER_NAME")

    # APPINSIGHTS_INSTRUMENTATIONKEY = os.environ.get("APPINSIGHTS_INSTRUMENTATIONKEY")

    STORAGE_ACCOUNT_NAME = "sachatbotdevsc01"
    STORAGE_ACCOUNT_KEY = "VReDCR7gPAMottpcY5D/bcSb8SXlN59EEmfXINeXNqLyX92XMSWcYua0ZcFvNSVbLDuttrVwRZBl+ASthdfF7Q=="
    OPENAI_AZURE_ENDPOINT = "https://openai-chatbot-dev-sc-01.openai.azure.com/"
    OPENAI_API_VERSION = "2024-02-15-preview"
    OPENAI_DEPLOYMENT_NAME = "gpt-4_1106"
    OPENAI_API_KEY = "41fcb4690ab846999e7ae58a8a997531"
    OPENAI_API_TYPE = "Azure"
    OPENAI_MODEL_NAME = "gpt-4"

    COSMOS_DB_ACCOUNT_URI = "https://poliseecosmosdb.documents.azure.com:443/"
    COSMOS_DB_ACCOUNT_KEY = "tekfDqIDvjjqnDvXtfijvtzMf8NILKtNw9jhnJqiSfHiwyEqvZJIeq9n0G9H2RefvGBGXtQK0WG3ACDbvlUmGQ=="
    COSMOS_DB_DATABASE_NAME = 'poliseedatabase'
    COSMOS_DB_CONTAINER_NAME = 'poliseecontainer'

    APPINSIGHTS_INSTRUMENTATIONKEY = "59cd21a6-4f0d-4759-aa9b-b918b94dec79"
else: 
    OPENAI_AZURE_ENDPOINT = get_secret(KEY_VAULT_URL,"OPENAI-AZURE-ENDPOINT")
    OPENAI_API_VERSION = get_secret(KEY_VAULT_URL,"OPENAI-API-VERSION")
    OPENAI_DEPLOYMENT_NAME = get_secret(KEY_VAULT_URL,"OPENAI-DEPLOYMENT-NAME")
    OPENAI_API_KEY = get_secret(KEY_VAULT_URL,"OPENAI-API-KEY")
    OPENAI_API_TYPE = get_secret(KEY_VAULT_URL,"OPENAI-API-TYPE")
    OPENAI_MODEL_NAME = get_secret(KEY_VAULT_URL,"OPENAI-MODEL-NAME")

    STORAGE_ACCOUNT_NAME = get_secret(KEY_VAULT_URL,"STORAGE-ACCOUNT-NAME") 
    STORAGE_ACCOUNT_KEY = get_secret(KEY_VAULT_URL,"STORAGE-ACCOUNT-KEY") 

    COSMOS_DB_ACCOUNT_URI = get_secret(KEY_VAULT_URL, "COSMOS-DB-ACCOUNT-URI")
    COSMOS_DB_ACCOUNT_KEY = get_secret(KEY_VAULT_URL, "COSMOS-DB-ACCOUNT-KEY")
    COSMOS_DB_DATABASE_NAME = get_secret(KEY_VAULT_URL, "COSMOS-DB-DATABASE-NAME")
    COSMOS_DB_CONTAINER_NAME = get_secret(KEY_VAULT_URL, "COSMOS-DB-CONTAINER-NAME")

    APPINSIGHTS_INSTRUMENTATIONKEY = get_secret(KEY_VAULT_URL, "APPINSIGHTS-INSTRUMENTATIONKEY")